version: '3.5'

services:
  go-tgbot:
    image: go-tgbot
    container_name: go-tgbot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    volumes:
      - ./.bin/:/app/